config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, path: '', 
      path_names: { sign_in: 'login', 
                    sign_out: 'logout',
                    sign_up: 'signup' },
      controllers: { registrations: 'registrations', 
                     confirmations: 'confirmations',
                     sessions: 'sessions' }

  # resources :pages, only: [:show]
  root 'pages#business_home'
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  resources :categories do
    get ':subcategory_id', to: 'subcategories#show', as: :subcategory
  end 
  get 'for-mentors', to: 'pages#mentors_home'
  namespace :calls do
    resources :history, only: [:index]
  end
  resources :calls, only: [:index, :show, :update] do
    get :reject, on: :member
  end

  resources :conference, only: [:show, :create, :update, :destroy]
  resources :dashboard, only: [:index]
  resources :account, only: [:index]
  resources :profiles, only: %i[show index]
  resources :settings, only: [:index, :create] do
    get :states, on: :collection
    get :cities, on: :collection
  end
  namespace :settings do
    resources :about, only: [:index, :create]
    resources :video, only: [:index, :create]
    resources :authenticate, only: [:index]
    resources :services, path: 'offerings', only: [:index]
    resources :categories, only: [:index, :create]
    resources :wallet, only: [:index, :create, :destroy, :update]
  end
  resources :assets, path: 'files'
  namespace :requests do
    resources :times, only: [:edit, :update]
  end
  resources :messages, only: :create
  resources :requests do
    scope module: 'requests' do
      resources :verify, only: [:index, :create]
    end
  end
  resources :inbox, only: [:index, :show] do
    collection do
      get 'all'
    end
  end
  get 'requests/:id/thankyou', to: 'requests#thankyou', as: :requests_thankyou
  resources :reviews
  resources :my_mentors, path: 'my-mentors', only: [:index]
  resources :payments, only: [:index, :show] do
    get 'received', on: :collection
  end
  resources :callbacks, only: :create
  resources :services, path: 'offerings'
  resources :wishlist, only: :index
  post 'wishlist/:service_id', to: 'wishlist#create', as: :wishlist_create
  resources :notifications, only: :show
  namespace :downloads do
    resources :assets, only: [:show]
  end
  resources :get_started, path: 'get-started', only: :index
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :update_first_time
  layout 'dashboard'

  def index
    @profile = current_user.profile
    @services = @profile.services.page(params[:page]).per(5)
    @message = DashboardMessageFinder.new(current_user).perform
  end

  private

  def update_first_time
    current_user.update(first_time: false)
  end
end

app/views/dashboard/_confirm_email_message.html.erb
<div class="alert alert-info text-center p-4" role="alert">
  <h4 class="alert-heading">Confirm Your Email</h4>
  <p class="mb-0">In order to get email notifications from Expercoin, you need to confirm your email address</p>
  <p>If you haven't received an email with confirmation instructions please contact <span class="strong">support@expercoin.com</span></p>
</div>

app/views/dashboard/_linkedin_message.html.erb
<div class="alert alert-info text-center p-4" role="alert">
  <h4 class="alert-heading">Verify Your Account With LinkedIn</h4>
  <p class="mb-0">Before you start selling on Expercoin there is one lost thing we need you to do.</p>
  <p>We require all of our sellers to verify their account with LinkedIn before we can publish your offer.</p>
  <a class="btn btn-primary btn-ln" href="/auth/linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i> Apply with LinkedIn</a>
</div>

app/views/dashboard/_offer_message.html.erb
<div class="alert alert-info text-center p-4" role="alert">
  <h4 class="alert-heading">Create A New Offer</h4>
  <p class="mb-0">Your Offer is the service that you sell on Expercoin. Creating your Offer is an opportunity to show off your talent and provide buyers with all the information they need to help them decide to do business with you.</p>
</div>

app/views/dashboard/_wallet_message.html.erb
<div class="alert alert-info text-center p-4" role="alert">
  <h4 class="alert-heading">You are almost done</h4>
  <p class="mb-0">There is one last thing we need you to do. In order to receive payments, please add your ETH Address to the wallet.</p>
  <p>Click the button bellow and then add your ETH Address to the wallet.</p>
  <%= link_to 'Go to Wallet', settings_wallet_index_path, class: 'btn btn-primary' %>
</div>

app/views/dashboard/index.html.erb
<main class="content">

  <header class="account-header-white">
    <div class="content-container content-with-aside">


      <div class="mentor-header content-main mentor-header-aligned">
        <div class="mentor-image mentor-image-sm">
          <%= render "shared/profile_photo", photo: current_user&.profile.try(:photo).thumb.url %>
        </div>
        <div class="mentor-info">
          <h1><%= decorate(current_user&.profile).full_name %></h1>
          <p><%= current_user&.profile.title %></p>
        </div>
      </div>
      <div class="mentor-dashboards">
        <ul class="mantor-dashboards-nav">
          <li>
            <%= link_to "My Requests", requests_path , class: '' %>
          </li>
          <li>
            <%= link_to "My Calls", calls_path , class: '' %>
          </li>  
          <li>
            <%= link_to inbox_index_path do %>
              Inbox <span class="unread-messages <%= 'has-unread-messages' if decorate(@profile).unread_messages? %>">(<%= decorate(@profile).unread_messages %>)</span>
            <% end %>  
          </li>       
        </ul>       
      </div>
    </div>
  </header>
  <div class="content-container">
      <%= render @message unless @message.nil? %>
  </div>
  <section class="content-container content-with-aside">
    <div class="content-main">
      <div class="content-title">
        <h3>My Offers</h3>
      </div>
      <div class="provider-offers">
        <% @services.each do |service| %>
          <%= render 'shared/msp/services_card', service: service, service_url: service_path(service) %>
        <% end %>
        <div class="service-container"> 
          <%= link_to new_service_path, class: 'service-card add-service' do %>
              <div class='plus'>+</div>
              Create a New Offer
          <% end %>
        </div>
      </div>
      <%= paginate @services %>
    </div>
    <div class="content-aside">
      <div class="mentor-container">
        <div class="mentor-card mentor-card-panoramic">
          <div class="card-hero">
            <%= render "shared/profile_photo", photo: @profile.photo.thumb.url %>
          </div>
          <div class="card-body">
            <h4><%= link_to decorate(@profile).full_name, profile_path(@profile) %></h4>
            <div class="mentor-title">
              <%= @profile.title %>
            </div>
            <div class="mentor-bio">
              <%= @profile.about&.html_safe %>
            </div>
            <div class="mentor-location">
              <i class="fa fa-map-marker"></i>
              <%= decorate(@profile).display_location_with_abbreviation %>
            </div>
          </div>
          <div class="card-footer">
            <div class="footer-block mentor-price" data-container="body" data-toggle="popover" data-placement="top" data-content="<%= ENV['CURRENCY'] %> <%= decorate(@profile).display_rate %>" data-trigger="hover">
                <%=  number_to_currency(decorate(@profile).display_rate_in_usd) %> per minute
            </div>
            <div class="footer-block mentor-reviews">
              <%= rating = ProfileRating.new(@profile).average_rating %>
              <%= display_stars(rating) %>
            </div>
            <div class="footer-block mentor-actions">
              <%= link_to "Edit Profile", settings_path, class: 'btn btn-footer' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>