config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, path: '', 
      path_names: { sign_in: 'login', 
                    sign_out: 'logout',
                    sign_up: 'signup' },
      controllers: { registrations: 'registrations', 
                     confirmations: 'confirmations',
                     sessions: 'sessions' }

  # resources :pages, only: [:show]
  root 'pages#business_home'
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  resources :categories do
    get ':subcategory_id', to: 'subcategories#show', as: :subcategory
  end 
  get 'for-mentors', to: 'pages#mentors_home'
  namespace :calls do
    resources :history, only: [:index]
  end
  resources :calls, only: [:index, :show, :update] do
    get :reject, on: :member
  end

  resources :conference, only: [:show, :create, :update, :destroy]
  resources :dashboard, only: [:index]
  resources :account, only: [:index]
  resources :profiles, only: %i[show index]
  resources :settings, only: [:index, :create] do
    get :states, on: :collection
    get :cities, on: :collection
  end
  namespace :settings do
    resources :about, only: [:index, :create]
    resources :video, only: [:index, :create]
    resources :authenticate, only: [:index]
    resources :services, path: 'offerings', only: [:index]
    resources :categories, only: [:index, :create]
    resources :wallet, only: [:index, :create, :destroy, :update]
  end
  resources :assets, path: 'files'
  namespace :requests do
    resources :times, only: [:edit, :update]
  end
  resources :messages, only: :create
  resources :requests do
    scope module: 'requests' do
      resources :verify, only: [:index, :create]
    end
  end
  resources :inbox, only: [:index, :show] do
    collection do
      get 'all'
    end
  end
  get 'requests/:id/thankyou', to: 'requests#thankyou', as: :requests_thankyou
  resources :reviews
  resources :my_mentors, path: 'my-mentors', only: [:index]
  resources :payments, only: [:index, :show] do
    get 'received', on: :collection
  end
  resources :callbacks, only: :create
  resources :services, path: 'offerings'
  resources :wishlist, only: :index
  post 'wishlist/:service_id', to: 'wishlist#create', as: :wishlist_create
  resources :notifications, only: :show
  namespace :downloads do
    resources :assets, only: [:show]
  end
  resources :get_started, path: 'get-started', only: :index
end

app/models/msp/conference/video.rb
module MSP
  module Conference
    # Stup class for Twilio
    class Video
      ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID']
      AUTH_TOKEN =  ENV['TWILIO_AUTH_TOKEN']
      API_VIDEO_KEY_SID = ENV['TWILIO_API_VIDEO_KEY_SID']
      API_VIDEO_KEY_SECRET = ENV['TWILIO_API_VIDEO_KEY_SECRET']
      
      attr_reader :client

      def initialize
        @client = Twilio::REST::Client.new(ACCOUNT_SID, AUTH_TOKEN)
      end

      def call; end

      def generate_access_token
        token = Twilio::JWT::AccessToken.new(
          ACCOUNT_SID,
          API_VIDEO_KEY_SID,
          API_VIDEO_KEY_SECRET
        )
        token
      end

      def grant_access_to_video(room)
        grant = Twilio::JWT::AccessToken::VideoGrant.new
        grant.room = room
        grant
      end

      def access_token(identity, room)
        token = generate_access_token
        grant = grant_access_to_video(room)
        token.add_grant(grant)
        token.identity = identity
        token.to_jwt
      end

      def create_room
        begin
          group_room = client.video.rooms.create(
            # unique_name: 'DailyStandup',
            # type: 'group',
            # record_participants_on_connect: true,
            # status_callback: 'http://example.org'
          )
          group_room.sid
        rescue StandardError
          false
        end
      end
      
      def find_room(room_sid)
        client.video.rooms(room_sid).fetch
        rescue StandardError
      end

      def room_closed?(room_sid)
        room = find_room(room_sid)
        return unless room
        room.status == 'completed'
      end

      def kill_room(room_sid)
        client.video.rooms(room_sid).update(status: 'completed')
      rescue StandardError
        'room does not exist'
      end
    end
  end
end

app/models/msp/email.rb
module MSP
  module Email
    def create_email_record(id, subject, meta)
      MailRecord.create(
        recipient_id: id,
        sent: true,
        subject: subject,
        meta: meta,
        mail_type: 'MSP'
      )
    end
  end
end

app/models/msp/update_request_status.rb
module MSP
  class UpdateRequestStatus
    def initialize(request)
      @request = request
    end

    def perform
      pending_status
      accepted_status
      verifying_status
      verified_status
      inprogress_status
      completed_status
    end

    private
    
    def pending_status
      return unless valid_for_pending_status?
      @request.update(status: 'pending')
    end

    def valid_for_pending_status?
      @request.draft?
    end

    def accepted_status
      return unless valid_for_accepted_status?
      @request.update(status: 'accepted')
    end

    def valid_for_accepted_status?
      @request.selected_date && @request.pending?
    end

    def verifying_status
      return unless valid_for_verifying_status?
      @request.update(status: 'verifying')
    end

    def valid_for_verifying_status?
      @request.tx_hash && @request.accepted? && !@request.eth_transaction
    end

    def verified_status
      return unless valid_for_verified_status?
      @request.update(status: 'verified')
    end

    def valid_for_verified_status?
      @request.eth_transaction && (@request.accepted? || @request.verifying?)
    end

    def inprogress_status
      return unless valid_for_inprogress_status?
      @request.update(status: 'inprogress')
    end

    def valid_for_inprogress_status?
      (@request.inviter || @request.invitee) && !@request.ended_at && @request.verified?
    end

    def completed_status
      return unless valid_for_completed_status?
      @request.update(status: 'completed')
    end

    def valid_for_completed_status?
      @request.ended_at && @request.inprogress?
    end
  end
end

app/views/shared/msp/_aside_buttons.html.erb
<div class="card-controls">
  <%= link_to 'Schedule a Session', new_request_path(expert: @profile), class: 'btn btn-block btn-with-icon btn-schedule' unless @profile == current_user.try(:profile) %>
  <a class="btn btn-block btn-with-icon btn-message" href="#" data-toggle="modal" data-target="#message-mentor-modal-<%= profile&.id %>">Send Message</a>
</div>

app/views/shared/msp/_delete_service_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="deleteServiceModal-<%= service.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteServiceModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure that you want to delete service <%= service.title %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        <%= link_to service_path(service), method: :delete do %>
          <button type="button" class="btn btn-danger">Delete</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/msp/_group_card.html.erb
<div class="group-container">
  <%= link_to group_url, class: "group-card" do %> 
    <div class="card-hero">
      <%= render "shared/group_photo", photo: group.cover.thumb.url %>
    </div>
    <div class="card-body">
      <h4><%= group.title %></h4>
    </div>
  <% end %>
</div>

app/views/shared/msp/_horizontal_profile_card.html.erb
<div class="mentor-card mentor-card-landscape">
  <div class="card-hero">
    <%= render "shared/profile_photo", photo: mentor.photo.thumb.url %>
    <div class='hero-price' data-container="body" data-toggle="popover" data-placement="bottom" data-content="<%= decorate(mentor).display_rate %>" data-trigger="hover">
      <strong><%= number_to_currency(decorate(mentor).display_rate_in_usd) %> per minute</strong>
    </div>
    <div class="hero-rating">
      <%= rating = ProfileRating.new(mentor).average_rating %>
      <%= display_stars(rating) %>
    </div>
  </div>
  <div class="card-body">
    <h4><%= link_to decorate(mentor).full_name, profile_path(mentor) %></h4>
    <div class="mentor-title">
      <%= mentor.title %>
    </div>
    <div class="mentor-location">
      <i class="fa fa-map-marker"></i>
      <%= decorate(mentor).display_location_with_abbreviation %>
    </div>
    <ul class="mentor-stats">
      <li>
        <%= display_stars(ProfileRating.new(mentor).student_rating(current_user), 'You Rated') %>
      </li>
      <li>Sessions <span class="strong"><%= mentor.requests.completed.count %></span></li>
      <li>Last Session <span class="strong"><%= decorate(mentor).last_session %></span></li>
    </ul>
    <a class="mentor-bio-collapse-link" data-toggle="collapse" data-target='#<%= "collapse_#{ mentor.id }" %>' aria-expanded="false" aria-controls='<%= "collapse_#{ mentor.id }" %>"'>
      View More
    </a>
    <div class="mentor-bio-collapse collapse" id='<%= "collapse_#{ mentor.id }" %>'>
      <%= mentor.about&.html_safe %>
    </div>
  </div>
  <div class="card-controls">
    <%= link_to 'Schedule a Session', request_url, class: 'btn btn-block btn-with-icon btn-schedule' unless mentor == current_user.try(:profile) %>
    <a class="btn btn-block btn-with-icon btn-message" href="#" data-toggle="modal" data-target="#message-mentor-modal-<%= mentor.id %>">Send Message</a>
  </div>
</div>
<%= render 'inbox/message_modal', profile: mentor %>

app/views/shared/msp/_horizontal_profile_card_two.html.erb
<div class="mentor-card mentor-card-landscape-two">
  <div class="card-main">
    <div class="card-hero">
      <%= render "shared/profile_photo", photo: mentor.photo.thumb.url %>
      <div class='hero-price' data-container="body" data-toggle="popover" data-placement="bottom" data-content="<%= decorate(mentor).expercoin_rate %>" data-trigger="hover">
        <strong><%= number_to_currency(decorate(mentor).display_rate_in_usd) %> per minute</strong>
      </div>
      <div class="hero-rating">
        <%= rating = ProfileRating.new(mentor).average_rating %>
        <%= display_stars(rating) %>
      </div>
    </div>
    <div class="card-body">
      <h4><%= link_to decorate(mentor).full_name, profile_path(mentor) %></h4>
      <div class="mentor-title">
        <%= mentor.title %>
      </div>
      <div class="mentor-location">
        <i class="fa fa-map-marker"></i>
        <%= decorate(mentor).display_location_with_abbreviation %>
      </div>
      <ul class="mentor-stats">
        <li>
          <%= display_stars(ProfileRating.new(mentor).student_rating(current_user), 'You Rated') %>
        </li>
        <li>Sessions <span class="strong"><%= mentor.requests.completed.count %></span></li>
        <li>Last Session <span class="strong"><%= decorate(mentor).last_session %></span></li>
      </ul>
      <a class="mentor-bio-collapse-link" data-toggle="collapse" data-target='#<%= "collapse_#{ mentor.id }" %>' aria-expanded="false" aria-controls='<%= "collapse_#{ mentor.id }" %>"'>
        View More
      </a>
      <div class="mentor-bio-collapse collapse" id='<%= "collapse_#{ mentor.id }" %>'>
        <%= mentor.about&.html_safe %>
      </div>
    </div>
  </div> 
  <div class="card-controls">
    <%= link_to 'Schedule a Session', request_url, class: 'btn btn-with-icon btn-schedule' unless mentor == current_user.try(:profile) %>
    <a class="btn btn-with-icon btn-message" href="#" data-toggle="modal" data-target="#message-mentor-modal-<%= mentor.id %>">Send Message</a>
  </div>
</div>
<%= render 'inbox/message_modal', profile: mentor %>

app/views/shared/msp/_join_request_room.html.erb
<% @request ||= req  %>
<div id='request' data-room-id="<%= @request.id %>">
  <% if decorate(@request).call_approved? %>
    <div class="request-accepted-time">
      <h6 class="request-time">Call session is schedulled for <%= decorate(@request).session_date %></h6>
      <% if decorate(@request).call_ready? %>
        <% if @request.inprogress? %>
          <%= link_to "Join Call", conference_path(@request.room_sid), class: "btn btn-success btn-md btn-md-lgr" %>
        <% elsif @request.verified? %> 
          <%= form_tag conference_index_path do %>
            <%= hidden_field_tag :request_id, @request.id %>
            <%= submit_tag "Request Call", class: "btn btn-success btn-md btn-md-lgr" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>  
  <% if @request.verified? %>
    <span id='update-page' date-time='<%= decorate(@request).selected_date.to_i %>'></span>
  <% end %>
</div>

app/views/shared/msp/_profile_card.html.erb
<% provider = service ? service : profile %>
<div class="mentor-container">
  <div class="mentor-card mentor-card-panoramic">
    <%# <% if profile.country == 'United States' %>
    <%#   <%= image_tag "usa_flag.png", class: "card-flag" %>
    <%# <% end %>
    <div class="card-hero">
      <%= render "shared/profile_photo", photo: profile.photo.thumb.url %>
    </div>
    <div class="card-body">
      <h4><%= link_to decorate(profile).full_name, profile_path(profile) %></h4>
      <div class="mentor-title">
        <%= profile.title %>
      </div>
      <div class="mentor-bio">
        <%= profile.about&.html_safe %>
      </div>
      <div class="mentor-location">
        <i class="fa fa-map-marker"></i>
        <%= decorate(profile).display_location_with_abbreviation %>
      </div>
    </div>
    <div class="card-footer">
      <div class="footer-block mentor-price" data-container="body" data-toggle="popover" data-placement="top" data-content="<%= ENV['CURRENCY'] %> <%= decorate(provider).display_rate %>" data-trigger="hover">
          <%=  number_to_currency(decorate(provider).display_rate_in_usd) %> per minute
      </div>
      <div class="footer-block mentor-reviews">
        <%= rating = ProfileRating.new(profile).average_rating %>
        <%= display_stars(rating) %>
      </div>
      <div class="footer-block mentor-actions">
        <% if profile == current_user.try(:profile) %>
          <button class="btn btn-footer" disabled>Schedule Session</button>
        <% else %>
          <%= link_to "Schedule Session", request_url, class: 'btn btn-footer' %>
        <% end %>  
        <!-- <a class="btn btn-footer-icon btn-message" href="#" data-toggle="modal" data-target="#message-mentor-modal-<%= profile.id %>"></a>
        <a class="btn btn-footer-icon btn-add"></a> -->
      </div>
    </div>

  </div>
</div>
  <%#= render 'shared/corporate/msp/message_mentor_modal', expert: expert %>

app/views/shared/msp/_services_card.html.erb
<div class="service-container">
  <div class="service-card"> 
    <div class="card-hero">
      <%= link_to service_url do %>
        <%= render 'shared/service_photo', photo: service.cover_image.thumb.url %>
      <% end %>  
    </div>
    <div class="card-body">
      <div class="service-owner">
        <% if service.owner.present? %>
          <%= render "shared/profile_photo", photo: service.owner.photo.badge.url %>
          <%= link_to decorate(service.owner).full_name, profile_path(service.owner) %>
        <% else %>
          <%= image_tag "expercoin_logo.png", class: 'expercoin-service' %>  
        <% end %>
      </div>
      <div class="service-title">
        <h4><%= link_to service.title, service_url %></h4>
      </div>
      <div class="service-rating-and-prices">
        <div class="pricing" data-container="body" data-toggle="popover" data-placement="top" data-content="<%= decorate(service).display_rate %>" data-trigger="hover">
          <span class="value"><%= number_to_currency(decorate(service).display_rate_in_usd) %></span>
          <span class="text">per minute</span>
        </div>
        <div class="rating-and-wishlist">
          <div class="rating">
            <%= decorate(service.owner).average_rating %>
            <%= display_stars(decorate(service.owner).average_rating) %>
          </div>
          <div class="wishlist">
            <% if current_user %>
              <%= link_to wishlist_create_path(service), remote: true, method: :post do %>
                <span id="wishlist-<%= service.id%>">
                  <i class="fa <%= service.wishlisted_by(current_user.try(&:profile)) ? 'fa-heart' : 'fa-heart-o' %>" aria-hidden="true"></i>
                </span>
              <% end %>
            <% end %>
          </div>  
        </div>
      </div>  
    </div>
    <% if service.owner.try(:id) == current_user.try(:id) %>
      <div class="card-controls">
        <%= link_to edit_service_path(service) do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>  
        <a href='javascript:void(0)' data-toggle="modal" data-target="#deleteServiceModal-<%= service.id %>">
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        </a>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/msp/delete_service_modal", service: service %>