config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, path: '', 
      path_names: { sign_in: 'login', 
                    sign_out: 'logout',
                    sign_up: 'signup' },
      controllers: { registrations: 'registrations', 
                     confirmations: 'confirmations',
                     sessions: 'sessions' }

  # resources :pages, only: [:show]
  root 'pages#business_home'
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  resources :categories do
    get ':subcategory_id', to: 'subcategories#show', as: :subcategory
  end 
  get 'for-mentors', to: 'pages#mentors_home'
  namespace :calls do
    resources :history, only: [:index]
  end
  resources :calls, only: [:index, :show, :update] do
    get :reject, on: :member
  end

  resources :conference, only: [:show, :create, :update, :destroy]
  resources :dashboard, only: [:index]
  resources :account, only: [:index]
  resources :profiles, only: %i[show index]
  resources :settings, only: [:index, :create] do
    get :states, on: :collection
    get :cities, on: :collection
  end
  namespace :settings do
    resources :about, only: [:index, :create]
    resources :video, only: [:index, :create]
    resources :authenticate, only: [:index]
    resources :services, path: 'offerings', only: [:index]
    resources :categories, only: [:index, :create]
    resources :wallet, only: [:index, :create, :destroy, :update]
  end
  resources :assets, path: 'files'
  namespace :requests do
    resources :times, only: [:edit, :update]
  end
  resources :messages, only: :create
  resources :requests do
    scope module: 'requests' do
      resources :verify, only: [:index, :create]
    end
  end
  resources :inbox, only: [:index, :show] do
    collection do
      get 'all'
    end
  end
  get 'requests/:id/thankyou', to: 'requests#thankyou', as: :requests_thankyou
  resources :reviews
  resources :my_mentors, path: 'my-mentors', only: [:index]
  resources :payments, only: [:index, :show] do
    get 'received', on: :collection
  end
  resources :callbacks, only: :create
  resources :services, path: 'offerings'
  resources :wishlist, only: :index
  post 'wishlist/:service_id', to: 'wishlist#create', as: :wishlist_create
  resources :notifications, only: :show
  namespace :downloads do
    resources :assets, only: [:show]
  end
  resources :get_started, path: 'get-started', only: :index
end

app/views/shared/_assets_form.html.erb
<%= form_with scope: :asset, url: assets_path, html: { class: 'd-none' } do |f| %>
  <% current_user&.assets&.clear if current_user&.assets&.any? %>
  <%= f.file_field :file %>
  <%= f.submit 'save' %>
<% end %>

app/views/shared/_call_client.html.erb
<div class='session-details-mentor'>
  <div class="mentor-header mentor-header-sm content-main">
    <div class="mentor-image">
      <%= render "shared/profile_photo", photo: profile.photo&.url %>
    </div>
    <div class="mentor-info">
      <span>Your Mentor</span>
      <h1><%= decorate(profile).full_name %></h1>
      <p><%= @expert.title %></p>
    </div>
    <div class='session-details-mentor-price-and-rating'>
      <div class='mentor-price' data-container="body" data-toggle="popover" data-placement="top" data-content="<%= ENV['CURRENCY'] %> <%= decorate(profile).display_rate %>" data-trigger="hover">
        <span class="strong"> <%= number_to_currency(decorate(profile).display_rate_in_usd) %></span> per minute
      </div>
      <div class='mentor-rating'>
        <p class="rating">
        <span class="text-uppercase">Rating</span>
        <%= display_stars(ProfileRating.new(profile).average_rating) %>
        </p>
      </div>
    </div>
  </div>
    
  <div class="session-details-request">
    <h4 class="strong title"><%= @request.title %></h4>
    <span class="category">Category: Marketing</span>
    <p><%= @request.message %></p>
  </div>
</div>

app/views/shared/_group_photo.erb
<%= image_tag photo %>

app/views/shared/_how_it_works.html.erb
<div class='panel'>
  <div class='panel-header'>
    <h5>How it works?</h5>
  </div>
  <div class='panel-body panel-body-paddingless'>
    <div id="accordion" class="hiw-accordian">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              1. Seek and Connect
            </button>
          </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">Send your request to a particular expert by browsing for the expertise or skillset you are looking for; or broadcast your request to our community of experts. Our matching algorithm will match you with the experts interested. All experts on our platform are pre-vetted. If you already have a preferred mentor, you can schedule your next session(s) with him/her. At this time, you will be pre-charged for the estimated length of the call, based on the expert’s per-minute rate.
          
          Enterprises can also buy a pack of one-on-one or group sessions for their employers. Please write to us for customized solution.</div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              2. Collaborate
            </button>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">Mentor collaborate with you in real time using tools such as screen sharing and video chat to get the most of your mentoring session. Whether it is technology review or code debugging, an expert is available to help you find the best way forward.</div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              3. Review
            </button>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body">At the conclusion of your session, you have the opportunity to rate your mentor across multiple dimensions such as subject matter expertise, professionalism, adherence to deadlines and cost. This cumulative rating determines the award of future engagemnets to the mentor and serves as an important motivator to do well and serve the needs of the mentees. Our platform holds every mentor accountable through this rating mechanism and other checks and balances.</div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              4. Manage & Measure
            </button>
          </h5>
        </div>
        <div id="collapseFour" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body">If you are a HR manager or a line manager, you can see how frequently your employees are using the mentorship platform and what kind of topics are hot within your group or company.
          
            You can buy mentorship credits in bulk and give access to your team, while setting spending limits at individual level and group level.
          
          We provide rich reports with usage patterns and analysis for your review.</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_live_mentoring_modal.html.erb
<div class="modal fade mentorship-modal" tabindex="-1" role="dialog" id="live-mentoring-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header flex-space-between text-white bg-dark">
        <button class="btn btn-default" data-dismiss="modal" aria-label="Close">Cancel</button>
        <h4 class="modal-title centered">
          <span class="msp-icon-live mr-1"></span> Live Mentoring
        </h4>
        <button class="btn btn-success">Continue</button>
      </div>
      <div class="modal-body">
        <div class='content-main'>
          <div class='request-form'>
            <%= form_for :request, url: '' do |f| %>
              <section class='panel form-section'>
                <div class='section-title'>
                  <h4>Get Next Available Mentor</h4>
                </div>
                <div class='form-group'>
                  <%= f.label :title, 'What do you need help with?' %>
                  <%= f.text_field :title, { class: 'form-control', placeholder: 'Title of your request'} %>
                </div>

                <div class='form-group'>
                  <%= f.label :message do %>
                    Request Details
                    <span class='sub-label'>35 characters minimum. More details, the better.</span>
                  <% end %>
                  </label>  
                  <%= f.text_area :message, { class: 'form-control', rows: 5 }%>
                </div>

                <div class='form-group'>
                  <%= f.label :category_id, 'Pick Expertise/Skill Area' %>
                  <%# <%= f.text_field :category_id, { class: 'select-picker-tags select-picker-with-padding full-width', data: { existing_tags: all_tags } } %>
                  <input type="text" class="form-control">
                </div>

                <div class='form-group'>
                  <%= f.label 'tags', 'Add Tags' %>
                  <%# <%= f.text_field :tag_list, {class: 'select-picker-tags select-picker-with-padding full-width', data: { existing_tags: all_tags}, value: '' } %>
                  <input type="text" class="form-control">
                </div>

                <div class='form-group'>
                  <%= f.label :requested_length, 'Aproximate Session Length' %>
                  <%= f.select :requested_length, options_for_select(['15min', '30min', '45min']), {}, { class: 'selectpicker selectpicker-with-padding full-width' } %>
                </div>

              </section>

              <%= f.submit 'Get Live Mentoring', class: 'btn btn-success btn-block' %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_login.html.erb
<div class="modal fade modal-account" id="modal_login" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { id: "login_user" }) do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, placeholder: t('form.fields.email'), class: 'form-control', id: 'login_user_email' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, autocomplete: "off", placeholder: t('form.fields.password'), class: 'form-control', id: 'login_user_password' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-success btn-md btn-block">Login</button>
          <span class="button-divider">Or</span>
          <a href="/auth/linkedin" class="btn btn-primary btn-md btn-block btn-ln"><i class="fa fa-linkedin" aria-hidden="true"></i> Login with LinkedIn</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_modal_signup.html.erb
<div class="modal fade modal-account" id="modal_signup" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :first_name, autofocus: true, placeholder: t('form.fields.first_name'), class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.text_field :last_name, autofocus: true, placeholder: t('form.fields.last_name'), class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, placeholder: t('form.fields.email'), class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, autocomplete: "off", placeholder: t('form.fields.password'), class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: t('form.fields.password_confirmation'), class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-success btn-md btn-block">Sign Up</button>
          <span class="button-divider">Or</span>
          <a href="/auth/linkedin" class="btn btn-primary btn-md btn-block btn-ln"><i class="fa fa-linkedin" aria-hidden="true"></i> Sign up with LinkedIn</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag "expercoin_logo.png" %>
    Expercoin
  <% end %>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_content" aria-controls="navbar_content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar_content">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown categories-dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Browse
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="inner-menu">
            <div class="categories-menu menu-block">  
              <% Category.main.each do |category| %>
                <a class="dropdown-item category-item" href="<%= category_path(category) %>" data-id="<%= category.id %>"><%= category.name %></a>
              <% end %>
            </div>
            <div class="subcategories-menu menu-block">
              <% Category.main.each do |category| %>
                <div class="category-subcategories" data-id="<%= category.id %>">
                  <div class="category-name"><%= category.name %></div>
                  <% category.subcategories.order(name: :asc).each do |subcategory| %>
                    <a class="dropdown-item subcategory-item" href="<%= category_subcategory_path(category, subcategory) %>"><%= subcategory.name %></a>
                  <% end %>
                </div>    
              <% end %>
            </div>
          </div>  
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <% if current_user.first_time %>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path,  method: :delete, class: "nav-link"%>
          </li>  
        <% else %>
          <li class="nav-item dropdown notification-dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="notification_dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if decorate(current_user.profile).unread_notifications? %>
                <i class="fa fa-bell" aria-hidden="true"></i>
                <span class="notification-counter"><%= decorate(current_user.profile).unread_notifications %></span>
              <% else %>
                <i class="fa fa-bell-slash" aria-hidden="true"></i>
              <% end %>  
            </a>
            <div class="dropdown-menu notifications" aria-labelledby="notification_dropdown">
              <%= render 'notifications/notifications', user: current_user %> 
            </div>
          </li>
          <li class="nav-item dropdown profile-dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="profile_dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= decorate(current_user.profile).full_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="profile_dropdown">
              <%= link_to 'Dashboard', dashboard_index_path, class: 'dropdown-item' %>
              <%= link_to 'Inbox', inbox_index_path, class: 'dropdown-item' %>
              <%= link_to 'Account', account_index_path, class: 'dropdown-item' %>
              <%= link_to 'Edit Profile', settings_path, class: 'dropdown-item' %>
              <%= link_to "Log Out", destroy_user_session_path,  method: :delete, class: "dropdown-item"%>
            </div>
          </li>
        <% end %>  
      <% else %>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#modal_signup">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#modal_login">Login</a>
        </li>
      <% end %>  
    </ul>
  </div>
</nav>

app/views/shared/_payment_navbar.html.erb
<nav class="content-nav">
  <div class="content-nav-container">
    <ul class="content-nav-list">
      <li>
        <%= link_to 'Send', payments_path  %>
      </li>
      <li>
        <%= link_to 'Received', received_payments_path %>
      </li>
    </ul>  
  </div>
</nav>

app/views/shared/_profile_navigation.html.erb
<div class="profile-sidebar">
  <div class="list-group side-nav-1">
    <a class="<%= ('active' if locals[:active] == 'basic_info') %> list-group-item" href="<%= settings_path %>">
      <span>
        <div class="basic-info-grey"></div>
      </span>
      Basic Info
    </a>
    <a class="<%= ('active' if locals[:active] == 'about') %> list-group-item" href="<%= settings_about_index_path %>">
      <span>
        <div class="basic-info-grey"></div>
      </span>
      About
    </a>
    <% if current_user.pending? %>
      <a class="<%= ('active' if locals[:active] == 'authenticate') %> list-group-item" href="<%= settings_authenticate_index_path %>">
        <span>
          <div class="basic-info-grey"></div>
        </span>
        Authenticate
      </a>
    <% end %>
    <a class="<%= ('active' if locals[:active] == 'video') %> list-group-item double-line-item" href="<%= settings_video_index_path %>">
      <span>
        <div class="help-grey"></div>
      </span>
      <span class="double-line">
        Your Video Pitch
      </span>
    </a>
    <a class="<%= ('active' if locals[:active] == 'services') %> list-group-item double-line-item" href="<%= settings_services_path %>">
      <span>
        <div class="help-grey"></div>
      </span>
      <span class="double-line">
        Your Offerings
      </span>
    </a>
    <a class="<%= ('active' if locals[:active] == 'find') %> list-group-item double-line-item" href="<%= settings_categories_path %>">
      <span>
        <div class="help-grey"></div>
      </span>
      <span class="double-line">
        Help people
        <br/>
        find you
      </span>
    </a>
    <a class="<%= ('active' if locals[:active] == 'address') %> list-group-item" href="<%= settings_wallet_index_path %>">
      <span>
        <div class="basic-info-grey"></div>
      </span>
      My Expercoin Wallet
    </a>
  </div>
</div>

app/views/shared/_profile_photo.html.erb
<% if photo.present? %>
  <%= image_tag photo, class: "img-circle" %>
<% else %>
  <%= image_tag 'empty_user.png', class: "img-circle" %>
<% end %>

app/views/shared/_request_review.html.erb
<div class="mentor-reviews request-info-reviews">
  <h2 class="title">Your Review</h2>
  <div id='output' data-transaction-screen></div>
  <% if review.nil? %>
    <%= form_for Review.new, url: reviews_path do |f| %>
      <%= f.hidden_field :tx_hash %>
      <%= f.hidden_field :request_id, value: req.id %>
      <div class="form-group">
        <%= f.label :rate %>
        <ul class="rating-stars">
          <input type="radio" id="star_0" name="review[rate]" value="1" checked/>
          <li><input type="radio" id="star_1" name="review[rate]" value="1" /><label for="star_1" class="star-label"><i class="fa fa-star-o"></i></label></li>
          <li><input type="radio" id="star_2" name="review[rate]" value="2" /><label for="star_2" class="star-label"><i class="fa fa-star-o"></i></label></li>
          <li><input type="radio" id="star_3" name="review[rate]" value="3" /><label for="star_3" class="star-label"><i class="fa fa-star-o"></i></label></li>
          <li><input type="radio" id="star_4" name="review[rate]" value="4" /><label for="star_4" class="star-label"><i class="fa fa-star-o"></i></label></li>
          <li><input type="radio" id="star_5" name="review[rate]" value="5" /><label for="star_5" class="star-label"><i class="fa fa-star-o"></i></label></li>
        </ul>
      </div>
      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, class: 'form-control', rows: '4' %>
      </div>
      <%= f.submit 'save', class: 'hidden', data: { 'review-form-submit': true } %>
      <button type='button' class='btn btn-primary btn-md btn-md-lgr' data-review-submit>
        Save
      </button>
    <% end %>
  <% else %>
    <div class="review">
      <div class="review-avatar">
        <%= render "shared/profile_photo", photo: review.author.photo&.url %>
      </div>
      <div class="review-body">
        <h4><a><%= decorate(review.author).full_name %></a></h4>
        <p class="quote">"<%= review.message %>"</p>
      </div>
      <div class="review-rating">
        <ul class="rating-data">
          <li>
            <%= display_stars review.rate %>
            (<%= review.rate %>)
          </li>
          <li>Posted <span class="strong"><%= review.created_at.strftime("%b %d, %Y")  %></span>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div> 
<script>
  window.done = false;
  $(document).on("turbolinks:load",function(){
    if($('[data-transaction-screen]').length) {
      $(document).on("click", "[data-review-submit]", function(){
        if (typeof web3 !== 'undefined') {
          window.web3 = new Web3(web3.currentProvider);
          var toAddress = "<%= ENV['ETH_ADDRESS'] %>";
          var ethAmount = <%= 0.0417334991420286e0 %>;
          var data = "<% expert ? 'Expert' : 'Client' %>" + " Review message: " + $('#review_message').val() + ", rate: "+ $('[name="review[rate]"]:checked').last().val();
          if(!window.done) {
            window.done = true;
            var abi = <%= raw Eth::Contract.abi.to_json %>;
            var contractAddress = '<%= Eth::Contract.new(@request.tx_hash).contract_address %>';
            var contract = web3.eth.contract(abi).at(contractAddress);

            function expertReview() {
              contract.expertReview.sendTransaction(data, {
                gas: '3000000',
                gasPrice: 1000000000
              },function (error, result){
                if(!error){
                  $('#review_tx_hash').val(result);
                  $('[data-review-form-submit]').click();
                }else{
                  console.log(error);
                }
              });
            };

            function clientReview() {
              contract.clientReview.sendTransaction(data, {
                gas: '3000000',
                gasPrice: 1000000000
              },function (error, result){
                if(!error){
                  $('#review_tx_hash').val(result);
                  $('[data-review-form-submit]').click();
                }else{
                  console.log(error);
                }
              });
            };
            <% if expert %>
              expertReview();
            <% else %>
              clientReview();
            <% end %>
          }
        } else {
          $('#output').html('Please download and install Metamask: <a href="https://metamask.io/">https://metamask.io/</a>');
        }
       });
    }
  });
</script>

app/views/shared/_search_requests.html.erb
<div class="panel requests-history-container">
  <div class="col-md-8 requests-history-item">
    <span class="requests-history-label">Request History</span>
  </div>
  <div class="col-md-4 requests-history-item">
    <%= form_tag(url, method: :get, enforce_utf8: false) do %>
      <i class="fa fa-search"></i>
      <%= text_field_tag :search, params[:search], class: "requests-history-search", placeholder: "Search Requests" %>
    <% end %>
  </div>
</div>

app/views/shared/_subnavbar.html.erb
<div class="content-nav-container">
  <ul class="content-nav-list">
    <li>
      <%= link_to 'Find Offerings', services_path, class: "#{'active' if active == 'mentors'}"  %>
    </li>
    <li>
      <%= link_to 'My Mentors', my_mentors_path, class: "#{'active' if active == 'my mentors'}"  %>
    </li>
    <li>
      <%= link_to 'My Requests', requests_path, class: "#{'active' if active == 'requests'}"  %>
    </li>
    <li>
      <%= link_to 'Wishlist', wishlist_index_path, class: "#{'active' if active == 'wishlist'}"  %>
    </li>
    <li>
      <%= link_to 'Payments', payments_path, class: "#{'active' if active == 'payments'}"  %>
    </li>
    <li>
      <div class='search-tab'>
        <%= form_tag(url, method: :get, enforce_utf8: false) do %>
          <i class="fa fa-search"></i>
          <%= text_field_tag :search, params[:search], class: "", placeholder: "Search Offerings" %>
        <% end %>
      </div>
    </li>
  </ul>
</div>