config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, path: '', 
      path_names: { sign_in: 'login', 
                    sign_out: 'logout',
                    sign_up: 'signup' },
      controllers: { registrations: 'registrations', 
                     confirmations: 'confirmations',
                     sessions: 'sessions' }

  # resources :pages, only: [:show]
  root 'pages#business_home'
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  resources :categories do
    get ':subcategory_id', to: 'subcategories#show', as: :subcategory
  end 
  get 'for-mentors', to: 'pages#mentors_home'
  namespace :calls do
    resources :history, only: [:index]
  end
  resources :calls, only: [:index, :show, :update] do
    get :reject, on: :member
  end

  resources :conference, only: [:show, :create, :update, :destroy]
  resources :dashboard, only: [:index]
  resources :account, only: [:index]
  resources :profiles, only: %i[show index]
  resources :settings, only: [:index, :create] do
    get :states, on: :collection
    get :cities, on: :collection
  end
  namespace :settings do
    resources :about, only: [:index, :create]
    resources :video, only: [:index, :create]
    resources :authenticate, only: [:index]
    resources :services, path: 'offerings', only: [:index]
    resources :categories, only: [:index, :create]
    resources :wallet, only: [:index, :create, :destroy, :update]
  end
  resources :assets, path: 'files'
  namespace :requests do
    resources :times, only: [:edit, :update]
  end
  resources :messages, only: :create
  resources :requests do
    scope module: 'requests' do
      resources :verify, only: [:index, :create]
    end
  end
  resources :inbox, only: [:index, :show] do
    collection do
      get 'all'
    end
  end
  get 'requests/:id/thankyou', to: 'requests#thankyou', as: :requests_thankyou
  resources :reviews
  resources :my_mentors, path: 'my-mentors', only: [:index]
  resources :payments, only: [:index, :show] do
    get 'received', on: :collection
  end
  resources :callbacks, only: :create
  resources :services, path: 'offerings'
  resources :wishlist, only: :index
  post 'wishlist/:service_id', to: 'wishlist#create', as: :wishlist_create
  resources :notifications, only: :show
  namespace :downloads do
    resources :assets, only: [:show]
  end
  resources :get_started, path: 'get-started', only: :index
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!

  def show
    @transaction = Transaction.find(params[:id])
    @profile = current_user.profile
  end

  def index
    transactions = SearchService.new(
      Transaction.where(sender: current_user.profile),
      params[:search]
    ).perform
    @transactions = transactions.page(params[:page]).per(8)
  end
end

app/views/payments/index.html.erb
<nav class="content-nav">
  <%= render "shared/subnavbar",  url: services_path, active: "payments" %>
</nav>
<main class="content content-with-nav">
  <div class="content-container user-requests">
    <div class="content-main">
      <%= render 'shared/search', url: payments_path, title: 'Payments History' %>

      <div class="panel requests-list-container" data-ordered-by="none" data-order-direction="none">
        <header class="requests-list-header">
          <div class="col-md-2 sortable-item" data-sort-type="date">
            Date
          </div>
          <div class="col-md-3 sortable-item" data-sort-type="date">
            Amount (<%= ENV['CURRENCY'] %>)
          </div>
          <div class="col-md-5 sortable-item" data-sort-type="date">
            Request
          </div>
          <div class="col-md-2" data-sort-type="status">
          </div>
        </header>
        <div class="row-items-container">
          <% @transactions.each do |transaction| %>
            <div class="requests-list-row" id="<%= transaction.id %>">
              <div class="col-md-2 requests-list-item">
                <%= transaction.created_at.to_date %>
              </div>
              <div class="col-md-2 requests-list-item">
                <%= decorate(transaction).display_amount %>
              </div>
              <div class="col-md-6 requests-list-item">
                <%= link_to transaction.request.title, request_path(transaction.request) %>  
              </div>
              <div class="col-md-2 requests-list-item flex-align-right">
                <%= link_to "Details", payment_path(transaction), class: "btn-table" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
        <%= paginate @transactions %>
  </div>
</main>

app/views/payments/received.html.erb
<nav class="content-nav">
  <div class="content-nav-container">
    <ul class="content-nav-list">
      <li>
        <%= link_to 'Send', payments_path %>
      </li>
      <li>
        <%= link_to 'Received', '#', class: 'active' %>
      </li>
    </ul>  
  </div>
</nav>
<main class="content content-with-nav">
  <div class="content-container user-requests">
    <div class="content-main">
      <%= render 'shared/search', url: inbox_index_path, title: 'Payments History' %>

      <div class="panel requests-list-container" data-ordered-by="none" data-order-direction="none">
        <header class="requests-list-header">
          <div class="col-md-3 sortable-item" data-sort-type="date">
            Sender
          </div>
          <div class="col-md-3 sortable-item" data-sort-type="date">
            Amount (<%= ENV['CURRENCY'] %>)
          </div>
          <div class="col-md-3 sortable-item" data-sort-type="date">
            Cost (<%= ENV['CURRENCY'] %>)
          </div>
          <div class="col-md-3 sortable-item" data-sort-type="status">
            Status
          </div>
        </header>
        <div class="row-items-container">
          <% @payments.each do |payment| %>
            <div class="requests-list-row" id="<%= payment.id %>">
              <div class="col-md-3 requests-list-item">
<%= link_to decorate(payment.receiver).full_name, profile_path(payment.sender) %>
              </div>
              <div class="col-md-3 requests-list-item">
                <%= payment.amount %>
              </div>
              <div class="col-md-3 requests-list-item">
                <%= payment.cost %>
              </div>
              <div class="col-md-3 requests-list-item flex-space-between">
                <span ><%= payment.status %></span>
                <%= link_to "Details", payment_path(payment), class: "btn-table" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%#= paginate @unread_messages %>
  </div>
</main>

app/views/payments/show.html.erb
<nav class="content-nav">
  <%= render "shared/subnavbar",  url: services_path, active: "payments" %>
</nav>
<main class="content content-with-nav">
  <section class="content-container mt-5">
    <div class="content-main">
      <div class="panel requests-history-container">
        <div class="col-md-12 requests-history-item">
          <span class="requests-history-label">Transaction Details</span>
        </div>
      </div>
      <div class="panel requests-list-container" data-ordered-by="none" data-order-direction="none">
        <div class="row-items-container">
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">Date: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= @transaction.created_at.to_date %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">Amount: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= "#{ENV['CURRENCY']} #{decorate(@transaction).display_amount }" %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">Transaction Hash: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= @transaction.tx_hash %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">Sender: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= decorate( @transaction.sender.profile ).full_name %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">From: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= @transaction.from_eth %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">To: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= @transaction.to_eth %>
              </div>
            </div>
            <div class="requests-list-row">
              <div class="col-md-3 requests-list-item">
                <h6 class="strong">Block Number: </h6>
              </div>
              <div class="col-md-9 requests-list-item">
                <%= @transaction.block_number %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </section>
</main>